name: Expo Deployment

on:
  push:
    branches: [develop]
  # pull_request:
  #   types: [closed]
  #   branches: [main]

jobs:
  Build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '9.0.4'
          java-package: jdk
          architecture: x64
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 5.x
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-password: ${{ secrets.EXPO_PASSWORD }}
      - name: Install deps
        working-directory: ./src/app
        run: npm install
      - name: Build Android APK Bundle
        working-directory: ./src/app
        run: expo build:android
